### ISSUE TITLE
Replace Optional with Option in doc code snippet

### ISSUE THREAD

**Issue by abbiemery** [DiamondLightSource/graph-federation#39]
In the docs here https://github.com/DiamondLightSource/graph-federation/blob/main/docs/how-tos/rust_service.md

The following code snippet in Defining Objects should have `preferred_name: Option<String>` instead of Optional. This is how it is defined in the rest of the examples.

```
use async_graphql::SimpleObject;

#[derive(SimpleObject)]
struct Person {
    id: u32, 
    first_name: String, 
    last_name: String, 
    preferred_name: Optional<String>,
}
```

**Comment by garryod** [comment]
Resolved with https://github.com/DiamondLightSource/graph-federation/commit/729c4c52c366f57a3b7a9c22c46dae1dde32ec9a
